#!/user/bin/env php

<?php

use app\commands\DataFeedCommand;
use Symfony\Component\Console\Application;

require __DIR__ . '/vendor/autoload.php';

$app = new Application('DataFeed');

$app->add(new DataFeedCommand());

try {
    $app->run();
} catch (Exception $e) {
    echo 'data File: ' . $e->getMessage() . PHP_EOL;
}
